version: '3'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=MySQL123!!
           - MYSQL_DATABASE=employeemanager
           - MYSQL_USER=root
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./employeemanagerback/
    ports:
           - "8081"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ./employeemanagerapp-master/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
      - "80:80"   

